CC = gcc
LIBS = -lpthread

#ARGS Tache 1

#ARGS = code/lecteurs_ecrivains
#ARGS = code/philosophes
ARGS = code/producteurs_consommateurs

#ARGS Tache 2 TS

#ARGS = Mutex_ts/lecteurs_ecrivains
#ARGS = philosophes
#ARGS = producteurs_consommateurs
#STRUCT= my_mutex

#ARGS = tache2/my_mutex

run:
	$(CC) -o $(ARGS) $(ARGS).c $(LIBS)
